[package]
name = "todo_app"
version = "0.1.0"
authors = ["Guilherme Campos"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "migration", "entities"]

[dependencies]
todo_app_api = { path = "api"}