version: '3.7'
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    volumes:
      - todo_rs:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgress_pass
      - POSTGRES_USER=todo_rs
      - POSTGRES_DB=todo_rs_db
      - TZ=America/Sao_Paulo
    networks:
      - todo_rs
networks:
  todo_rs:
    external: true
volumes:
  todo_rs: